name: "Docs Build"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: pip
        cache-dependency-path: pyproject.toml
    - name: Install dependencies
      run: |
        # Install local package with tests dependencies extras
        python -m pip install --upgrade pip
        pip install -e ".[docs]"
    - name: directly build sphinx
      run: |
        make html
      with:
        docs-folder: "docs/"
    - uses: actions/upload-artifact@v4
      with:
        name: DocumentationHTML
        path: docs/_build/html/
